export const sportsData = {
  futbol: {
    leagues: [
      {
        name: "super-lig",
        slug: "super-lig",
        country: "Türkiye",

        standings: [
          {
            rank: 1,
            team: "Galatasaray",
            play: 22,
            win: 17,
            draw: 4,
            lose: 1,
            goalFor: 55,
            goalAgainst: 15,
            avg: 40,
            point: 55,
          },
          {
            rank: 2,
            team: "Fenerbahçe",
            play: 22,
            win: 15,
            draw: 7,
            lose: 0,
            goalFor: 51,
            goalAgainst: 20,
            avg: 31,
            point: 52,
          },
          {
            rank: 3,
            team: "Trabzonspor",
            play: 22,
            win: 13,
            draw: 6,
            lose: 3,
            goalFor: 43,
            goalAgainst: 26,
            avg: 17,
            point: 45,
          },
          {
            rank: 4,
            team: "Göztepe",
            play: 22,
            win: 11,
            draw: 8,
            lose: 3,
            goalFor: 27,
            goalAgainst: 12,
            avg: 15,
            point: 41,
          },
          {
            rank: 5,
            team: "Beşiktaş",
            play: 22,
            win: 11,
            draw: 7,
            lose: 4,
            goalFor: 40,
            goalAgainst: 29,
            avg: 11,
            point: 40,
          },
          {
            rank: 6,
            team: "Başakşehir",
            play: 22,
            win: 9,
            draw: 6,
            lose: 7,
            goalFor: 38,
            goalAgainst: 25,
            avg: 13,
            point: 33,
          },
          {
            rank: 7,
            team: "Kocaelispor",
            play: 22,
            win: 8,
            draw: 6,
            lose: 8,
            goalFor: 21,
            goalAgainst: 22,
            avg: -1,
            point: 30,
          },
          {
            rank: 8,
            team: "Samsunspor",
            play: 22,
            win: 7,
            draw: 9,
            lose: 6,
            goalFor: 25,
            goalAgainst: 27,
            avg: -2,
            point: 30,
          },
          {
            rank: 9,
            team: "Gaziantep FK",
            play: 22,
            win: 7,
            draw: 7,
            lose: 8,
            goalFor: 29,
            goalAgainst: 38,
            avg: -9,
            point: 28,
          },
          {
            rank: 10,
            team: "Alanyaspor",
            play: 22,
            win: 5,
            draw: 11,
            lose: 6,
            goalFor: 24,
            goalAgainst: 25,
            avg: -1,
            point: 26,
          },
          {
            rank: 11,
            team: "Gençlerbirliği",
            play: 22,
            win: 6,
            draw: 5,
            lose: 11,
            goalFor: 28,
            goalAgainst: 33,
            avg: -5,
            point: 23,
          },
          {
            rank: 12,
            team: "Antalyaspor",
            play: 22,
            win: 6,
            draw: 5,
            lose: 11,
            goalFor: 22,
            goalAgainst: 35,
            avg: -13,
            point: 23,
          },
          {
            rank: 13,
            team: "Rizespor",
            play: 22,
            win: 4,
            draw: 9,
            lose: 9,
            goalFor: 26,
            goalAgainst: 35,
            avg: -9,
            point: 21,
          },
          {
            rank: 14,
            team: "Konyaspor",
            play: 22,
            win: 4,
            draw: 8,
            lose: 10,
            goalFor: 25,
            goalAgainst: 35,
            avg: -10,
            point: 20,
          },
          {
            rank: 15,
            team: "Kasımpaşa",
            play: 22,
            win: 4,
            draw: 7,
            lose: 11,
            goalFor: 19,
            goalAgainst: 31,
            avg: -12,
            point: 19,
          },
          {
            rank: 16,
            team: "Eyüpspor",
            play: 22,
            win: 4,
            draw: 6,
            lose: 12,
            goalFor: 18,
            goalAgainst: 35,
            avg: -17,
            point: 18,
          },
          {
            rank: 17,
            team: "Kayserispor",
            play: 22,
            win: 2,
            draw: 10,
            lose: 10,
            goalFor: 17,
            goalAgainst: 43,
            avg: -26,
            point: 16,
          },
          {
            rank: 18,
            team: "Karagümrük",
            play: 22,
            win: 3,
            draw: 3,
            lose: 16,
            goalFor: 20,
            goalAgainst: 42,
            avg: -22,
            point: 12,
          },
        ],
      },

      {
        name: "premier-lig",
        slug: "premier-lig",
        country: "İngiltere",

        standings: [
          {
            rank: 1,
            team: "Arsenal",
            play: 26,
            win: 17,
            draw: 6,
            lose: 3,
            goalFor: 50,
            goalAgainst: 18,
            avg: 32,
            point: 57,
          },
          {
            rank: 2,
            team: "Manchester City",
            play: 26,
            win: 16,
            draw: 5,
            lose: 5,
            goalFor: 54,
            goalAgainst: 24,
            avg: 30,
            point: 53,
          },
          {
            rank: 3,
            team: "Aston Villa",
            play: 26,
            win: 15,
            draw: 5,
            lose: 6,
            goalFor: 37,
            goalAgainst: 27,
            avg: 10,
            point: 50,
          },
          {
            rank: 4,
            team: "Manchester United",
            play: 26,
            win: 12,
            draw: 9,
            lose: 5,
            goalFor: 47,
            goalAgainst: 37,
            avg: 10,
            point: 45,
          },
          {
            rank: 5,
            team: "Chelsea",
            play: 26,
            win: 12,
            draw: 8,
            lose: 6,
            goalFor: 47,
            goalAgainst: 30,
            avg: 17,
            point: 44,
          },
          {
            rank: 6,
            team: "Liverpool",
            play: 26,
            win: 12,
            draw: 6,
            lose: 8,
            goalFor: 41,
            goalAgainst: 35,
            avg: 6,
            point: 42,
          },
          {
            rank: 7,
            team: "Brentford",
            play: 26,
            win: 12,
            draw: 4,
            lose: 10,
            goalFor: 40,
            goalAgainst: 35,
            avg: 5,
            point: 40,
          },
          {
            rank: 8,
            team: "Everton",
            play: 26,
            win: 10,
            draw: 7,
            lose: 9,
            goalFor: 29,
            goalAgainst: 30,
            avg: -1,
            point: 37,
          },
          {
            rank: 9,
            team: "Bournemouth",
            play: 26,
            win: 9,
            draw: 10,
            lose: 7,
            goalFor: 43,
            goalAgainst: 45,
            avg: -2,
            point: 37,
          },
          {
            rank: 10,
            team: "Newcastle United",
            play: 26,
            win: 10,
            draw: 6,
            lose: 10,
            goalFor: 37,
            goalAgainst: 37,
            avg: 0,
            point: 36,
          },
          {
            rank: 11,
            team: "Sunderland",
            play: 26,
            win: 9,
            draw: 9,
            lose: 8,
            goalFor: 27,
            goalAgainst: 30,
            avg: -3,
            point: 36,
          },
          {
            rank: 12,
            team: "Fulham",
            play: 26,
            win: 10,
            draw: 4,
            lose: 12,
            goalFor: 35,
            goalAgainst: 40,
            avg: -5,
            point: 34,
          },
          {
            rank: 13,
            team: "Crystal Palace",
            play: 26,
            win: 8,
            draw: 8,
            lose: 10,
            goalFor: 28,
            goalAgainst: 32,
            avg: -4,
            point: 32,
          },
          {
            rank: 14,
            team: "Brighton",
            play: 26,
            win: 7,
            draw: 10,
            lose: 9,
            goalFor: 34,
            goalAgainst: 34,
            avg: 0,
            point: 31,
          },
          {
            rank: 15,
            team: "Leeds United",
            play: 26,
            win: 7,
            draw: 9,
            lose: 10,
            goalFor: 36,
            goalAgainst: 45,
            avg: -9,
            point: 30,
          },
          {
            rank: 16,
            team: "Tottenham",
            play: 26,
            win: 7,
            draw: 8,
            lose: 11,
            goalFor: 36,
            goalAgainst: 37,
            avg: -1,
            point: 29,
          },
          {
            rank: 17,
            team: "Nottingham Forest",
            play: 26,
            win: 7,
            draw: 6,
            lose: 13,
            goalFor: 25,
            goalAgainst: 38,
            avg: -13,
            point: 27,
          },
          {
            rank: 18,
            team: "West Ham United",
            play: 26,
            win: 6,
            draw: 6,
            lose: 14,
            goalFor: 32,
            goalAgainst: 49,
            avg: -17,
            point: 24,
          },
          {
            rank: 19,
            team: "Burnley",
            play: 26,
            win: 4,
            draw: 6,
            lose: 16,
            goalFor: 28,
            goalAgainst: 51,
            avg: -23,
            point: 18,
          },
          {
            rank: 20,
            team: "Wolverhampton",
            play: 26,
            win: 1,
            draw: 6,
            lose: 19,
            goalFor: 16,
            goalAgainst: 48,
            avg: -32,
            point: 9,
          },
        ],
      },

      {
        name: "la-liga",
        slug: "la-liga",
        country: "İspanya",

        standings: [
          {
            rank: 1,
            team: "Real Madrid",
            play: 24,
            win: 19,
            draw: 3,
            lose: 2,
            goalFor: 53,
            goalAgainst: 19,
            avg: 34,
            point: 60,
          },
          {
            rank: 2,
            team: "Barcelona",
            play: 24,
            win: 19,
            draw: 1,
            lose: 4,
            goalFor: 64,
            goalAgainst: 25,
            avg: 39,
            point: 58,
          },
          {
            rank: 3,
            team: "Villarreal",
            play: 23,
            win: 14,
            draw: 3,
            lose: 6,
            goalFor: 44,
            goalAgainst: 26,
            avg: 18,
            point: 45,
          },
          {
            rank: 4,
            team: "Atletico Madrid",
            play: 24,
            win: 13,
            draw: 6,
            lose: 5,
            goalFor: 38,
            goalAgainst: 21,
            avg: 17,
            point: 45,
          },
          {
            rank: 5,
            team: "Real Betis",
            play: 24,
            win: 11,
            draw: 8,
            lose: 5,
            goalFor: 39,
            goalAgainst: 29,
            avg: 10,
            point: 41,
          },
          {
            rank: 6,
            team: "Espanyol",
            play: 24,
            win: 10,
            draw: 5,
            lose: 9,
            goalFor: 29,
            goalAgainst: 33,
            avg: -4,
            point: 35,
          },
          {
            rank: 7,
            team: "Celta Vigo",
            play: 24,
            win: 8,
            draw: 10,
            lose: 6,
            goalFor: 32,
            goalAgainst: 27,
            avg: 5,
            point: 34,
          },
          {
            rank: 8,
            team: "Real Sociedad",
            play: 24,
            win: 8,
            draw: 7,
            lose: 9,
            goalFor: 34,
            goalAgainst: 35,
            avg: -1,
            point: 31,
          },
          {
            rank: 9,
            team: "Athletic Bilbao",
            play: 24,
            win: 9,
            draw: 4,
            lose: 11,
            goalFor: 27,
            goalAgainst: 34,
            avg: -7,
            point: 31,
          },
          {
            rank: 10,
            team: "Osasuna",
            play: 24,
            win: 8,
            draw: 6,
            lose: 10,
            goalFor: 28,
            goalAgainst: 28,
            avg: 0,
            point: 30,
          },
          {
            rank: 11,
            team: "Getafe",
            play: 24,
            win: 8,
            draw: 5,
            lose: 11,
            goalFor: 20,
            goalAgainst: 28,
            avg: -8,
            point: 29,
          },
          {
            rank: 12,
            team: "Girona",
            play: 24,
            win: 7,
            draw: 8,
            lose: 9,
            goalFor: 24,
            goalAgainst: 38,
            avg: -14,
            point: 29,
          },
          {
            rank: 13,
            team: "Sevilla",
            play: 24,
            win: 7,
            draw: 5,
            lose: 12,
            goalFor: 31,
            goalAgainst: 39,
            avg: -8,
            point: 26,
          },
          {
            rank: 14,
            team: "Alaves",
            play: 24,
            win: 7,
            draw: 5,
            lose: 12,
            goalFor: 21,
            goalAgainst: 30,
            avg: -9,
            point: 26,
          },
          {
            rank: 15,
            team: "Valencia",
            play: 24,
            win: 6,
            draw: 8,
            lose: 10,
            goalFor: 25,
            goalAgainst: 37,
            avg: -12,
            point: 26,
          },
          {
            rank: 16,
            team: "Elche",
            play: 24,
            win: 5,
            draw: 10,
            lose: 9,
            goalFor: 31,
            goalAgainst: 35,
            avg: -4,
            point: 25,
          },
          {
            rank: 17,
            team: "Rayo Vallecano",
            play: 23,
            win: 6,
            draw: 7,
            lose: 10,
            goalFor: 21,
            goalAgainst: 30,
            avg: -9,
            point: 25,
          },
          {
            rank: 18,
            team: "Mallorca",
            play: 24,
            win: 6,
            draw: 6,
            lose: 12,
            goalFor: 29,
            goalAgainst: 39,
            avg: -10,
            point: 24,
          },
          {
            rank: 19,
            team: "Levante",
            play: 23,
            win: 4,
            draw: 6,
            lose: 13,
            goalFor: 26,
            goalAgainst: 40,
            avg: -14,
            point: 18,
          },
          {
            rank: 20,
            team: "Oviedo",
            play: 23,
            win: 3,
            draw: 7,
            lose: 13,
            goalFor: 13,
            goalAgainst: 36,
            avg: -23,
            point: 16,
          },
        ],
      },
    ],
  },

  basketbol: {
    leagues: [
      {
        name: "nba",
        slug: "nba",

        standings: [
          { rank: 1, team: "Pistons", win: 40, lose: 13, pct: 0.755 },
          { rank: 2, team: "Celtics", win: 35, lose: 19, pct: 0.648 },
          { rank: 3, team: "Knicks", win: 35, lose: 20, pct: 0.636 },
          { rank: 4, team: "Cavaliers", win: 34, lose: 21, pct: 0.618 },
          { rank: 5, team: "Raptors", win: 32, lose: 23, pct: 0.582 },
          { rank: 6, team: "76ers", win: 30, lose: 24, pct: 0.556 },
          { rank: 7, team: "Magic", win: 28, lose: 25, pct: 0.528 },
          { rank: 8, team: "Heat", win: 29, lose: 27, pct: 0.518 },
          { rank: 9, team: "Hornets", win: 26, lose: 29, pct: 0.473 },
          { rank: 10, team: "Hawks", win: 26, lose: 30, pct: 0.464 },
          { rank: 11, team: "Bulls", win: 24, lose: 31, pct: 0.436 },
          { rank: 12, team: "Bucks", win: 23, lose: 30, pct: 0.434 },
          { rank: 13, team: "Nets", win: 15, lose: 38, pct: 0.283 },
          { rank: 14, team: "Pacers", win: 15, lose: 40, pct: 0.273 },
          { rank: 15, team: "Wizards", win: 14, lose: 39, pct: 0.264 },
        ],
      },

      {
        name: "euroleague",
        slug: "euroleague",

        standings: [
          { rank: 1, team: "Fenerbahçe", win: 20, lose: 7, pf: 2229, pa: 2139 },
          { rank: 2, team: "Olimpiakos", win: 18, lose: 9, pf: 2427, pa: 2248 },
          { rank: 3, team: "Valensiya", win: 18, lose: 10, pf: 2516, pa: 2401 },
          {
            rank: 4,
            team: "Real Madrid",
            win: 17,
            lose: 11,
            pf: 2441,
            pa: 2331,
          },
          { rank: 5, team: "Barcelona", win: 17, lose: 11, pf: 2378, pa: 2349 },
          {
            rank: 6,
            team: "Hapoel Tel Aviv",
            win: 16,
            lose: 11,
            pf: 2307,
            pa: 2217,
          },
          { rank: 7, team: "Zalgiris", win: 16, lose: 12, pf: 2483, pa: 2330 },
          { rank: 8, team: "Monaco", win: 16, lose: 12, pf: 2525, pa: 2390 },
          {
            rank: 9,
            team: "Panathinaikos",
            win: 16,
            lose: 12,
            pf: 2385,
            pa: 2340,
          },
          {
            rank: 10,
            team: "Kızılyıldız",
            win: 16,
            lose: 12,
            pf: 2433,
            pa: 2392,
          },
          {
            rank: 11,
            team: "Dubai Basket",
            win: 14,
            lose: 14,
            pf: 2443,
            pa: 2453,
          },
          {
            rank: 12,
            team: "Olimpia Milano",
            win: 14,
            lose: 14,
            pf: 2365,
            pa: 2391,
          },
          {
            rank: 13,
            team: "Makkabi Tel Aviv",
            win: 13,
            lose: 15,
            pf: 2483,
            pa: 2551,
          },
          { rank: 14, team: "Bayern", win: 12, lose: 16, pf: 2257, pa: 2331 },
          {
            rank: 15,
            team: "Virtus Bologna",
            win: 12,
            lose: 16,
            pf: 2277,
            pa: 2364,
          },
          { rank: 16, team: "Paris", win: 9, lose: 18, pf: 2402, pa: 2474 },
          {
            rank: 17,
            team: "Anadolu Efes",
            win: 9,
            lose: 19,
            pf: 2205,
            pa: 2297,
          },
          { rank: 18, team: "Baskonya", win: 9, lose: 19, pf: 2418, pa: 2531 },
          { rank: 19, team: "Partizan", win: 9, lose: 19, pf: 2226, pa: 2453 },
          {
            rank: 20,
            team: "Lyon-Villeurbanne",
            win: 7,
            lose: 21,
            pf: 2167,
            pa: 2385,
          },
        ],
      },
    ],
  },

  voleybol: {
    leagues: [
      { name: "Sultanlar Ligi", slug: "sultanlar-ligi" },
      { name: "CEV Şampiyonlar Ligi", slug: "cev" },
    ],
  },

  diger: {
    leagues: [
      { name: "Tenis", slug: "tenis" },
      { name: "Formula 1", slug: "f1" },
      { name: "UFC", slug: "ufc" },
    ],
  },
};
