export const sportsData = {
  basketbol: {
    leagues: [
      {
        name: "nba",
        slug: "nba",

        standings: [
          { rank: 1, team: "Pistons", win: 40, lose: 13, pct: 0.755 },
          { rank: 2, team: "Celtics", win: 35, lose: 19, pct: 0.648 },
          { rank: 3, team: "Knicks", win: 35, lose: 20, pct: 0.636 },
          { rank: 4, team: "Cavaliers", win: 34, lose: 21, pct: 0.618 },
          { rank: 5, team: "Raptors", win: 32, lose: 23, pct: 0.582 },
          { rank: 6, team: "76ers", win: 30, lose: 24, pct: 0.556 },
          { rank: 7, team: "Magic", win: 28, lose: 25, pct: 0.528 },
          { rank: 8, team: "Heat", win: 29, lose: 27, pct: 0.518 },
          { rank: 9, team: "Hornets", win: 26, lose: 29, pct: 0.473 },
          { rank: 10, team: "Hawks", win: 26, lose: 30, pct: 0.464 },
          { rank: 11, team: "Bulls", win: 24, lose: 31, pct: 0.436 },
          { rank: 12, team: "Bucks", win: 23, lose: 30, pct: 0.434 },
          { rank: 13, team: "Nets", win: 15, lose: 38, pct: 0.283 },
          { rank: 14, team: "Pacers", win: 15, lose: 40, pct: 0.273 },
          { rank: 15, team: "Wizards", win: 14, lose: 39, pct: 0.264 },
        ],
      },

      {
        name: "euroleague",
        slug: "euroleague",

        standings: [
          { rank: 1, team: "Fenerbahçe", win: 20, lose: 7, pf: 2229, pa: 2139 },
          { rank: 2, team: "Olimpiakos", win: 18, lose: 9, pf: 2427, pa: 2248 },
          { rank: 3, team: "Valensiya", win: 18, lose: 10, pf: 2516, pa: 2401 },
          {
            rank: 4,
            team: "Real Madrid",
            win: 17,
            lose: 11,
            pf: 2441,
            pa: 2331,
          },
          { rank: 5, team: "Barcelona", win: 17, lose: 11, pf: 2378, pa: 2349 },
          {
            rank: 6,
            team: "Hapoel Tel Aviv",
            win: 16,
            lose: 11,
            pf: 2307,
            pa: 2217,
          },
          { rank: 7, team: "Zalgiris", win: 16, lose: 12, pf: 2483, pa: 2330 },
          { rank: 8, team: "Monaco", win: 16, lose: 12, pf: 2525, pa: 2390 },
          {
            rank: 9,
            team: "Panathinaikos",
            win: 16,
            lose: 12,
            pf: 2385,
            pa: 2340,
          },
          {
            rank: 10,
            team: "Kızılyıldız",
            win: 16,
            lose: 12,
            pf: 2433,
            pa: 2392,
          },
          {
            rank: 11,
            team: "Dubai Basket",
            win: 14,
            lose: 14,
            pf: 2443,
            pa: 2453,
          },
          {
            rank: 12,
            team: "Olimpia Milano",
            win: 14,
            lose: 14,
            pf: 2365,
            pa: 2391,
          },
          {
            rank: 13,
            team: "Makkabi Tel Aviv",
            win: 13,
            lose: 15,
            pf: 2483,
            pa: 2551,
          },
          { rank: 14, team: "Bayern", win: 12, lose: 16, pf: 2257, pa: 2331 },
          {
            rank: 15,
            team: "Virtus Bologna",
            win: 12,
            lose: 16,
            pf: 2277,
            pa: 2364,
          },
          { rank: 16, team: "Paris", win: 9, lose: 18, pf: 2402, pa: 2474 },
          {
            rank: 17,
            team: "Anadolu Efes",
            win: 9,
            lose: 19,
            pf: 2205,
            pa: 2297,
          },
          { rank: 18, team: "Baskonya", win: 9, lose: 19, pf: 2418, pa: 2531 },
          { rank: 19, team: "Partizan", win: 9, lose: 19, pf: 2226, pa: 2453 },
          {
            rank: 20,
            team: "Lyon-Villeurbanne",
            win: 7,
            lose: 21,
            pf: 2167,
            pa: 2385,
          },
        ],
      },
    ],
  },

  voleybol: {
    leagues: [
      { name: "Sultanlar Ligi", slug: "sultanlar-ligi" },
      { name: "CEV Şampiyonlar Ligi", slug: "cev" },
    ],
  },

  diger: {
    leagues: [
      { name: "Tenis", slug: "tenis" },
      { name: "Formula 1", slug: "f1" },
      { name: "UFC", slug: "ufc" },
    ],
  },
};
